### ISSUE TITLE
output file names

### ISSUE THREAD

**Issue by aclum** [microbiomedata/metaT_ReadCounts#1]
The files names are correct in the end to end workflow but not in the isolated component workflow which is what nmdc_automation will use.Update output file names from readcount.wdl to be ~{prefix}.rnaseq_gea.txt and ~{prefix}.rnaseq_gea.intergenic.txt to match the output of the end to end workflow.

**Comment by kaijli** [comment]
done, jaws run 84188

**Comment by aclum** [comment]
Looks good, please merge these changes and bump the version file so we can use this version for workflow automation.
